# Generated by Django 2.2.1 on 2019-07-25 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='commentupvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='postupvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='posts.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='commentupvote',
            unique_together={('comment', 'user')},
        ),
    ]
